### ISSUE TITLE
Specify "testing" in installation part of README

### ISSUE THREAD

**Issue by VRRobbie** [kalepeterson/InetSysDev-GH-Community-Health#33]
The readme is really clean and nice, but I was just a little confused for when I first installed ghdata, I thought I could go directly to local host and use your guy's additions. It took me a bit to realize that reading a bit further in the readme had the very simple instructions with all the links that you guys provide to test out everything.  I would recommend just specifying in the installation portion to "read below" for showing that you guys provide links for testing.

**Comment by kalepeterson** [comment]
Good point, that's kinda confusing.  I added a note pointing to the testing section.  Would be nice if I could link to it, but I couldn't figure out how to do that (I don't think it's an actual section on the page...), so hopefully this is good enough for now.  Thanks!

**Comment by kalepeterson** [comment]
Resolved in pull request #37
