### ISSUE TITLE
Determine Which Metrics to Implement

### ISSUE THREAD

**Issue by jknust** [kalepeterson/InetSysDev-GH-Community-Health#7]
Metrics over time
Aggregate metrics

These will be functions in our module.

**Comment by jknust** [comment]
Open issues vs Contributors.

**Comment by kalepeterson** [comment]
Notes from 2/20 lecture (these might not be possible to build, but good to think about):
1. Organizational Drop-Off (Identify organizations.  Over/at time)
2. Path to Maintainership (How does someone become a maintainer? How far through that process do most contributors get? Company path alignment / steering)
3. Upstream/Downstream Engagement (Upstream: How likely are problems from other projects? Downstream: Does this project have impact?)
4. License Coverage (percentage of files that have licenses)

Former internal IP:
1. Code Base Diversity (Corporate diversity, gender diversity?)
2. Correlations Between Communities (Community dependencies / influence, health of related repos)
3. Stars for PR ("Vanity metric" for success of Public Relations)

Foundation monitoring of on-boarded / internally developed communities:
1. Code contributor diversity
2. Maturity changes (Age / Stability of project over time, pull req.s)
3. Release Management - Release Against Bugs (# Bug Issues after a release)

**Comment by kalepeterson** [comment]
Updated SystemDescription.md to include some preliminary metrics that Jared and I thought up.

**Comment by kalepeterson** [comment]
Lecture today included discussion on a working group that tries to develop metrics irrespective of repository or technology.  We can contribute in a limited way (specific to GitHub) by developing tooling (or attempting to do so) for calculating the metrics.

**Comment by kalepeterson** [comment]
Ultimately decided on aggregating metrics by time and adding the Relative Activity and Actions by Type metrics.
